version: '3.8'
services:
  php:
    container_name: php
    build: ./
    ports:
      - 3000:80
    environment:
      - XDEBUG_CONFIG=remote_host=host.docker.internal
      - ENV PHP_OPCACHE_ENABLE=0
      - PHP_REVALIDATE_FREQ=30
      - PHP_OPCACHE_MAX_ACCELERATED_FILES=10000
      - PHP_OPCACHE_MEMORY_CONSUMPTION=192
      - PHP_OPCACHE_MAX_WASTED_PERCENTAGE=10
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
      - PHP_OPCACHE_ENABLE=1
    volumes:
      - ./myapp:/myapp

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./docker/mysql-schemas/:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 3001:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
